# Generated by Django 5.0.6 on 2024-08-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CrowdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(choices=[('GML', '地球の正体'), ('CM3', 'プログラム名'), ('S44', 'TOMIKEN')], max_length=20)),
                ('crowd_level', models.IntegerField(verbose_name='Crowd Level')),
                ('pub_date', models.DateTimeField(verbose_name='pub_date')),
            ],
        ),
    ]
