# Generated by Django 5.0.7 on 2024-08-07 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_alter_crowddata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='location',
            field=models.CharField(choices=[('CM3', 'プログラム名'), ('GML', '地球の正体'), ('S44', 'TOMIKEN')], max_length=20),
        ),
    ]
