# Generated by Django 5.0.7 on 2024-08-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_alter_crowddata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='location',
            field=models.CharField(choices=[('S44', 'TOMIKEN'), ('CM3', 'プログラム名'), ('GML', '地球の正体')], max_length=20),
        ),
    ]
