# Generated by Django 5.0.7 on 2024-08-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_alter_crowddata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='location',
            field=models.CharField(choices=[('GML', '地球の正体'), ('CM3', 'プログラム名'), ('S44', 'TOMIKEN')], max_length=20),
        ),
    ]
