# Generated by Django 5.0.7 on 2024-08-13 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0014_alter_crowddata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='location',
            field=models.CharField(choices=[('S44', 'TOMIKEN'), ('GML', '地球の正体'), ('CM3', 'プログラム名')], max_length=20),
        ),
    ]
