# Generated by Django 5.0.7 on 2024-08-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0017_alter_crowddata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='location',
            field=models.CharField(choices=[('COMMUNICATIONCAT3', 'プログラム名'), ('S44', 'TOMIKEN'), ('GEOROGYLABOLATORY', '地球の正体')], max_length=20),
        ),
    ]
