# Generated by Django 5.0.6 on 2024-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0020_alter_crowddata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='location',
            field=models.CharField(choices=[('S44', 'TOMIKEN'), ('COMMUNICATIONCAT3', 'プログラム名'), ('GEOROGYLABOLATORY', '地球の正体'), ('S43', 'S43'), ('理科調査研究室', '理科調査研究室'), ('S70', 'S70'), ('S71', 'S71'), ('S72', 'S72'), ('S73', 'S73'), ('S74', 'S74')], max_length=20),
        ),
    ]
