# Generated by Django 5.1 on 2024-08-21 03:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0021_alter_crowddata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='crowd_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Crowd Level'),
        ),
    ]
