# Generated by Django 5.1 on 2024-09-01 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0022_alter_crowddata_crowd_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='crowd_level',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='混雑状況もしくは並び時間'),
        ),
        migrations.AlterField(
            model_name='crowddata',
            name='location',
            field=models.CharField(choices=[('S44', 'TOMIKEN'), ('COMMUNICATIONCAT3', 'プログラム名'), ('GEOROGYLABOLATORY', '地球の正体'), ('S43', 'S43'), ('理科調査研究室', '理科調査研究室'), ('S70', 'S70'), ('S71', 'S71'), ('S72', 'S72'), ('S73', 'S73'), ('S74', 'S74')], max_length=20, verbose_name='場所'),
        ),
    ]
