# Generated by Django 5.1 on 2024-09-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0024_alter_crowddata_crowd_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crowddata',
            name='location',
            field=models.CharField(choices=[('S45', '根城はサイコロを振らない'), ('情報教室1', '情報工学部 ゲーム展'), ('生徒昇降口,3FS34前PCラウンジ', '緑の羽根募金'), ('S46', 'ふっ、おもしれーゲーム'), ('S37,S38', 'ロボパーティーForBetting'), ('コミュニケーションコート', 'パフェって504通りあんねん'), ('柔剣道場', 'トレトレかるた')], max_length=20, verbose_name='場所'),
        ),
    ]
